# Write your MySQL query statement below
SELECT ROUND(
    COUNT(DISTINCT A.PLAYER_ID) /
    (SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY),
    2
) AS FRACTION
FROM ACTIVITY A
WHERE DATEDIFF(
    A.EVENT_DATE,
    (
        SELECT MIN(EVENT_DATE)
        FROM ACTIVITY 
        WHERE PLAYER_ID = A.PLAYER_ID
    )
) = 1;
