# Write your MySQL query statement below
SELECT 
ROUND(AVG(CASE WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1 ELSE 0 END*100),2) AS
IMMEDIATE_PERCENTAGE FROM DELIVERY AS D
WHERE ORDER_DATE = (
    SELECT MIN(ORDER_DATE) FROM DELIVERY 
    WHERE CUSTOMER_ID = D.CUSTOMER_ID
)